import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "@/hooks/useAuth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Finance App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " text-zinc-200 bg-zinc-950 h-screen flex items-center justify-center flex-col "
        }
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
